### ISSUE TITLE
Cannot compile on Mac

### ISSUE THREAD

**Issue by KaboomFox** [BTCPrivate/BitcoinPrivate#102]
### Describe the issue
when running `/btcputil/build-mac.sh -j$(sysctl -n hw.physicalcpu)`

I get the error 

```locator_tests.o -MD -MP -MF test/.deps/test_test_bitcoin-allocator_tests.Tpo -c -o test/test_test_bitcoin-allocator_tests.o `test -f 'test/allocator_tests.cpp' || echo './'`test/allocator_tests.cpp
wallet/asyncrpcoperation_shieldcoinbase.cpp: In member function 'UniValue AsyncRPCOperation_shieldcoinbase::perform_joinsplit(ShieldCoinbaseJSInfo&)':
wallet/asyncrpcoperation_shieldcoinbase.cpp:332:28: error: no matching function for call to 'JSDescription::Randomized(ZCJoinSplit&, uint256&, uint256&, boost::array<libzcash::JSInput, 2ul>&, boost::array<libzcash::JSOutput, 2ul>&, boost::array<long unsigned int, 2ul>&, boost::array<long unsigned int, 2ul>&, CAmount&, CAmount&, bool)'
             !this->testmode);
                            ^
In file included from ./primitives/block.h:9:0,
                 from ./chain.h:10,
                 from ./main.h:14,
                 from wallet/asyncrpcoperation_shieldcoinbase.cpp:9:
./primitives/transaction.h:83:26: note: candidate: static JSDescription JSDescription::Randomized(ZCJoinSplit&, const uint256&, const uint256&, boost::array<libzcash::JSInput, 2ul>&, boost::array<libzcash::JSOutput, 2ul>&, boost::array<long long unsigned int, 2ul>&, boost::array<long long unsigned int, 2ul>&, CAmount, CAmount, bool, std::function<int(int)>)
     static JSDescription Randomized(
          ```
### Can you reliably reproduce the issue?
#### If so, please list the steps to reproduce below:
1. on a mac follow the install instructions




### The version of Bitcoin Private you were using:

Master branch

**Comment by ch4ot1c** [comment]
Got the same thing. Caused by https://github.com/BTCPrivate/BitcoinPrivate/commit/28f9592c82427ecab1a7dbfbb1cd5130e4deae1e and https://github.com/BTCPrivate/BitcoinPrivate/commit/21137994c3bbda40b5343752e1bf10976c6c0125

**Comment by ch4ot1c** [comment]
https://github.com/BTCPrivate/BitcoinPrivate/pull/114 resolves
